version: "3"

services:
  postgres:
    container_name: "bookmarky-db"
    image: "mysql:latest"
    ports:
      - "3306:3306"
    environment:
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
      MYSQL_DATABASE: bookmarky
