version: "3"

services:
  postgres:
    container_name: "bookmarky-db"
    image: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: bookmarky
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
